<?php

namespace app\modules\apiv1\controllers;

//use yii\web\Controller;

use app\models\Pacientepatologia;
use app\modules\apiv1\models\Paciente;
use app\models\PacienteSearch;
use app\models\Usuario;
use yii\web\Controller;
use Yii;
use yii\rest\ActiveController;
use yii\behaviors\TimestampBehavior;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\ContentNegotiator;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

/**
 * Default controller for the `apiv1` module
 */
class PacienteController extends DefaultController
{
    public $modelClass = Paciente::class;

    public function beforeAction($action)
    {
        if ($action->id == 'create') {
            Yii::$app->db->beginTransaction();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function afterAction($action, $result)
    {
        if ($action->id == 'create') {
            $params = Yii::$app->getRequest()->getBodyParams();
            if (isset($params['patologia'])) {
                foreach ($params['patologia'] as $pat_id) {
                    $model = new Pacientepatologia(['[paciente_id' => $result->id, 'patologia_id' => $pat_id]);
                    if (!$model->save()) {
                        $result->addErrors($model->getErrors());
                    }
                }
            }
            $transaction = Yii::$app->db->getTransaction();
            if (!$result->hasErrors()) {
                $transaction->commit();
            } else {
                $transaction->rollBack();
            }
        }
        return parent::afterAction($action, $result);
    }

    public function actions()
    {
        $actions = parent::actions();
        $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProvider'];
        return $actions;
    }

    public function prepareDataProvider()
    {
        $searchModel = new PacienteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $dataProvider;
    }
}
